### ISSUE TITLE
example for compiling

### ISSUE THREAD

**Issue by paul-billgo** [coreos/issue-sync#51]
attempting to build on Mac OS with homebrew go1.12.4 installed

seeing the following output
can't load package: package github.com/coreos/issue-sync: cannot find package "github.com/coreos/issue-sync" in any of:
	/usr/local/Cellar/go/1.12.4/libexec/src/github.com/coreos/issue-sync (from $GOROOT)
	/Users/paulcesario/go/src/github.com/coreos/issue-sync (from $GOPATH)

can you provide example or instructions on how to build?

**Comment by crfeliz** [comment]
Hey Paul. Just to clarify: did you install via the `go get` command or did you clone the repo directly? If the former then issue-sync should have been copied to the $GOPATH (you may need to set this yourself if homebrew didn't set it for you when you installed go). If the latter then you need to `cd` into the issue-sync source directory and run `go build`. That will generate the issue-sync executable in the same directory which you can run there or copy to some directory on your $PATH.

**Comment by paul-billgo** [comment]
Thank you crfeliz. It wasn't in my $GOPATH. i rebuilt and am moving forward.
